# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
CNC execution spec types.
"""

import builtins
from raygeo import ops
from raygeo.ops import convert
import typing
__all__ = [
    "AggregateGroup",
    "AggregateInput",
    "AggregateOutput",
    "AggregateSpec",
    "ComputePayload",
    "EncodeSpec",
    "LinkMode",
    "MachineParams",
    "MachineTransformSpec",
    "Marker",
    "RotaryMappingSpec",
]

@typing.final
class AggregateGroup:
    r"""
    A group of inputs within an ``AggregateSpec``.
    
    Each group emits its own start/end markers, processes its inputs
    in order (optionally linking consecutive inputs when
    ``link_mode`` is ``Sequential``), and supports per-input placement
    and scaling.
    """
    @property
    def start_markers(self) -> builtins.list[Marker]:
        r"""
        Markers emitted before this group's inputs.
        """
    @property
    def inputs(self) -> builtins.list[AggregateInput]:
        r"""
        Upstream inputs to concatenate (in order).
        """
    @property
    def end_markers(self) -> builtins.list[Marker]:
        r"""
        Markers emitted after this group's inputs.
        """
    @property
    def link_mode(self) -> LinkMode:
        r"""
        Inter-input linking control (default ``LinkMode.none()``).
        """
    def __new__(cls, start_markers: typing.Sequence[Marker], inputs: typing.Sequence[AggregateInput], end_markers: typing.Sequence[Marker], link_mode: typing.Optional[LinkMode] = None) -> AggregateGroup: ...

@typing.final
class AggregateInput:
    r"""
    A single source input in an ``AggregateGroup``.
    
    Identifies an upstream node by key and optionally applies a
    placement matrix and uniform scaling.
    """
    @property
    def source_key(self) -> builtins.str:
        r"""
        Key of the upstream node whose Ops to consume.
        """
    @property
    def placement_matrix(self) -> builtins.list[builtins.list[builtins.float]]:
        r"""
        4×4 placement matrix (row-major) applied to all points in
        the source Ops.
        """
    @property
    def uid(self) -> builtins.str:
        r"""
        Optional UID carried through for marker correlation (not
        used by the pipeline core).
        """
    @property
    def target_dimensions(self) -> tuple[builtins.float, builtins.float]:
        r"""
        Target dimensions for uniform scaling ``(width, height)``.
        When ``(0, 0)`` (default), no scaling is applied.
        """
    def __new__(cls, source_key: builtins.str, placement_matrix: typing.Sequence[typing.Sequence[builtins.float]], uid: builtins.str = '', target_dimensions: tuple[builtins.float, builtins.float] = (0.0, 0.0)) -> AggregateInput: ...

@typing.final
class AggregateOutput:
    r"""
    Result of the ``Aggregate`` stage.
    
    Produced when the pipeline executes an ``AggregateSpec`` and contains
    the concatenated/transformed Ops together with an optional time
    estimate.
    """
    @property
    def ops(self) -> ops.Ops:
        r"""
        The concatenated Ops from all inputs in the aggregate.
        """
    @property
    def time_estimate(self) -> typing.Optional[builtins.float]:
        r"""
        Estimated machining time in seconds, or ``None`` when the
        ``MachineParams`` rates are all zero.
        """
    @property
    def ops_len(self) -> builtins.int:
        r"""
        Number of commands in the aggregated Ops.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class AggregateSpec:
    r"""
    Configuration for the ``Aggregate`` stage.
    
    An aggregate concatenates Ops from multiple upstream nodes, wraps
    them in markers (job/layer/workpiece start/end), applies per-input
    placement and scaling, optionally links consecutive inputs with
    travel moves, and applies batch transformers.
    """
    @property
    def wrap_start(self) -> builtins.list[Marker]:
        r"""
        Markers emitted before all groups (e.g. ``JobStart``).
        """
    @property
    def groups(self) -> builtins.list[AggregateGroup]:
        r"""
        Groups of inputs, each processed in order.
        """
    @property
    def wrap_end(self) -> builtins.list[Marker]:
        r"""
        Markers emitted after all groups (e.g. ``JobEnd``).
        """
    @property
    def machine(self) -> MachineParams:
        r"""
        Machine parameters for time estimation.
        """
    @property
    def transformers(self) -> builtins.list[typing.Any]:
        r"""
        Batch transformers applied to the aggregated Ops.
        """
    @transformers.setter
    def transformers(self, value: typing.Sequence[typing.Any]) -> None:
        r"""
        Batch transformers applied to the aggregated Ops.
        """
    def __new__(cls, wrap_start: typing.Sequence[Marker], groups: typing.Sequence[AggregateGroup], wrap_end: typing.Sequence[Marker], machine: MachineParams, transformers: typing.Sequence[typing.Any] = []) -> AggregateSpec: ...

@typing.final
class ComputePayload:
    r"""
    Opaque parameter bundle for a ``Compute`` stage node.
    
    The pipeline's ``StageSpec.Compute`` stores this as an opaque
    ``Any`` — the CNC converter unpacks it during traversal.
    
    :param assembler: The assembler spec that drives this compute.
    :param workpiece_uid: Stable identifier for section ownership.
    :param transformers: Optional list of transformer specs.
    :param state_source_keys: Keys of upstream nodes whose cleared-area
        state should be threaded into this compute (CNC only).
    """
    @property
    def assembler(self) -> typing.Any:
        r"""
        The assembler spec (e.g. ``ContourSpec``, ``AdaptiveClearingSpec``).
        """
    @property
    def workpiece_uid(self) -> builtins.str:
        r"""
        Stable workpiece identifier copied into emitted Ops sections.
        """
    @workpiece_uid.setter
    def workpiece_uid(self, value: builtins.str) -> None:
        r"""
        Stable workpiece identifier copied into emitted Ops sections.
        """
    @property
    def transformers(self) -> builtins.list[typing.Any]:
        r"""
        Optional list of transformer specs applied post-assembly.
        """
    @transformers.setter
    def transformers(self, value: typing.Sequence[typing.Any]) -> None:
        r"""
        Optional list of transformer specs applied post-assembly.
        """
    @property
    def state_source_keys(self) -> builtins.list[builtins.str]:
        r"""
        Source keys for cleared-area state threading (CNC only).
        """
    @state_source_keys.setter
    def state_source_keys(self, value: typing.Sequence[builtins.str]) -> None:
        r"""
        Source keys for cleared-area state threading (CNC only).
        """
    @property
    def power(self) -> builtins.float:
        r"""
        Laser power fraction (0.0 – 1.0) injected as ``SetPower``.
        """
    @power.setter
    def power(self, value: builtins.float) -> None:
        r"""
        Laser power fraction (0.0 – 1.0) injected as ``SetPower``.
        """
    @property
    def cut_speed(self) -> builtins.int:
        r"""
        Cut speed (mm/min) injected as ``SetFeedRate``.
        """
    @cut_speed.setter
    def cut_speed(self, value: builtins.int) -> None:
        r"""
        Cut speed (mm/min) injected as ``SetFeedRate``.
        """
    @property
    def rapid_speed(self) -> builtins.int:
        r"""
        Rapid speed (mm/min) injected as ``SetRapidRate``.
        """
    @rapid_speed.setter
    def rapid_speed(self, value: builtins.int) -> None:
        r"""
        Rapid speed (mm/min) injected as ``SetRapidRate``.
        """
    @property
    def head_uid(self) -> typing.Optional[builtins.str]:
        r"""
        Active head/laser UID injected as ``SetHead``.
        """
    @head_uid.setter
    def head_uid(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Active head/laser UID injected as ``SetHead``.
        """
    @property
    def air_assist(self) -> typing.Optional[builtins.bool]:
        r"""
        Air-assist state injected as ``SetAirAssist`` when provided.
        """
    @air_assist.setter
    def air_assist(self, value: typing.Optional[builtins.bool]) -> None:
        r"""
        Air-assist state injected as ``SetAirAssist`` when provided.
        """
    @property
    def frequency(self) -> builtins.int:
        r"""
        Laser frequency (Hz) injected as ``SetFrequency`` when positive.
        """
    @frequency.setter
    def frequency(self, value: builtins.int) -> None:
        r"""
        Laser frequency (Hz) injected as ``SetFrequency`` when positive.
        """
    @property
    def pulse_width(self) -> builtins.float:
        r"""
        Laser pulse width (µs) injected as ``SetPulseWidth`` when positive.
        """
    @pulse_width.setter
    def pulse_width(self, value: builtins.float) -> None:
        r"""
        Laser pulse width (µs) injected as ``SetPulseWidth`` when positive.
        """
    @property
    def profile(self) -> builtins.bool:
        r"""
        Print a profiling report to stdout after this node's faces have
        been assembled (default False).
        """
    @profile.setter
    def profile(self, value: builtins.bool) -> None:
        r"""
        Print a profiling report to stdout after this node's faces have
        been assembled (default False).
        """
    def __new__(cls, assembler: typing.Any, transformers: typing.Sequence[typing.Any] = [], state_source_keys: typing.Sequence[builtins.str] = [], power: builtins.float = 0.0, cut_speed: builtins.int = 0, rapid_speed: builtins.int = 0, head_uid: typing.Optional[builtins.str] = None, air_assist: typing.Optional[builtins.bool] = None, frequency: builtins.int = 0, pulse_width: builtins.float = 0.0, profile: builtins.bool = False, workpiece_uid: builtins.str = '') -> ComputePayload: ...

@typing.final
class EncodeSpec:
    r"""
    An encode-only compute stage.
    
    The pipeline's generic ``StageSpec`` has no ``Encode`` variant —
    encoding is a CNC concern. Use ``EncodeSpec`` when you need to
    run an encoder through the pipeline.
    """
    @property
    def source_key(self) -> builtins.str:
        r"""
        Key of the upstream node whose Ops to encode.
        """
    @property
    def encoder(self) -> convert.Encoder:
        r"""
        The encoder to use (e.g. ``GcodeSpec``, ``VertexSpec``).
        """
    def __new__(cls, source_key: builtins.str, encoder: convert.Encoder) -> EncodeSpec: ...

@typing.final
class LinkMode:
    r"""
    Controls inter-input linking in an AggregateGroup.
    
    Create via class methods:
      LinkMode.none()
      LinkMode.sequential(safe_z=2.0)
    """
    @property
    def tag(self) -> builtins.str:
        r"""
        Discriminant: ``"none"`` or ``"sequential"``.
        """
    @property
    def safe_z(self) -> builtins.float:
        r"""
        Safe Z height for retract/lift moves (only meaningful when
        ``tag == "sequential"``).
        """
    @classmethod
    def none(cls) -> LinkMode:
        r"""
        Create a ``LinkMode`` with no inter-input linking.
        """
    @classmethod
    def sequential(cls, safe_z: builtins.float) -> LinkMode:
        r"""
        Create a ``LinkMode`` that emits travel moves (retract →
        XY travel → plunge) between consecutive inputs.
        
        :param safe_z: Z height for retract and final lift.
        """

@typing.final
class MachineParams:
    r"""
    Feed/speed rates used for time estimation.
    
    All three fields default to ``0.0``, which disables the time
    estimate (returning ``None``).
    """
    @property
    def default_feed_rate(self) -> builtins.float:
        r"""
        Default feed rate (mm/min) for cutting moves.
        """
    @property
    def default_rapid_rate(self) -> builtins.float:
        r"""
        Default rapid rate (mm/min) for travel moves.
        """
    @property
    def acceleration(self) -> builtins.float:
        r"""
        Acceleration (mm/s²) for time estimation.
        """
    def __new__(cls, default_feed_rate: builtins.float = 0.0, default_rapid_rate: builtins.float = 0.0, acceleration: builtins.float = 0.0) -> MachineParams: ...

@typing.final
class MachineTransformSpec:
    r"""
    Configuration for the machine-transform pipeline stage.
    
    Converts world-space Ops into machine-space Ops by applying
    curve linearization, per-layer rotary axis mapping, world→machine
    coordinate transforms, WCS offsets, Z-flip, and AXIS_REPLACEMENT
    downstream conversion.
    """
    @property
    def source_key(self) -> builtins.str:
        r"""
        Key of the upstream node whose Ops to transform.
        """
    @property
    def linearize_arcs(self) -> builtins.bool:
        r"""
        When true, linearize arcs before other transforms.
        """
    @property
    def linearize_curves(self) -> builtins.bool:
        r"""
        When true, linearize Bezier curves before other transforms.
        """
    @property
    def world_to_machine(self) -> builtins.list[builtins.list[builtins.float]]:
        r"""
        4×4 world→machine matrix (row-major).
        """
    @property
    def default_wcs_offset(self) -> builtins.list[builtins.float]:
        r"""
        Default per-layer WCS command offset (x, y, z).
        """
    @property
    def layer_wcs_offsets(self) -> builtins.list[tuple[builtins.str, builtins.list[builtins.float]]]:
        r"""
        Per-layer WCS offsets, keyed by layer UID.
        """
    @property
    def reverse_z(self) -> builtins.bool:
        r"""
        When true, negate Z after transforms.
        """
    @property
    def rotary_mappings(self) -> builtins.list[RotaryMappingSpec]:
        r"""
        Per-layer rotary mapping configs.
        """
    def __new__(cls, source_key: builtins.str, linearize_arcs: builtins.bool, linearize_curves: builtins.bool, world_to_machine: typing.Sequence[typing.Sequence[builtins.float]], default_wcs_offset: typing.Sequence[builtins.float], layer_wcs_offsets: typing.Sequence[tuple[builtins.str, typing.Sequence[builtins.float]]], reverse_z: builtins.bool, rotary_mappings: typing.Sequence[RotaryMappingSpec]) -> MachineTransformSpec: ...

class Marker:
    r"""
    Declarative markers for aggregate groups.
    
    Each variant has a ``_tag`` field (always ``True``) required by the
    stub generator; pass it as keyword argument:
    
      Marker.JobStart(_tag=True)
      Marker.LayerStart(uid="my-layer", _tag=True)
      Marker.WorkpieceEnd(uid="my-wp", _tag=True)
      Marker.ProcessStart(uid="cut-1", params="{...}", _tag=True)
    """
    @typing.final
    class JobStart(Marker):
        r"""
        Marks the beginning of a job.
        """
        __match_args__ = ("_tag",)
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, _tag: builtins.bool) -> Marker.JobStart: ...
    
    @typing.final
    class JobEnd(Marker):
        r"""
        Marks the end of a job.
        """
        __match_args__ = ("_tag",)
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, _tag: builtins.bool) -> Marker.JobEnd: ...
    
    @typing.final
    class LayerStart(Marker):
        r"""
        Marks the start of a layer with the given UID.
        """
        __match_args__ = ("uid", "_tag",)
        @property
        def uid(self) -> builtins.str: ...
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, uid: builtins.str, _tag: builtins.bool) -> Marker.LayerStart: ...
    
    @typing.final
    class LayerEnd(Marker):
        r"""
        Marks the end of a layer with the given UID.
        """
        __match_args__ = ("uid", "_tag",)
        @property
        def uid(self) -> builtins.str: ...
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, uid: builtins.str, _tag: builtins.bool) -> Marker.LayerEnd: ...
    
    @typing.final
    class WorkpieceStart(Marker):
        r"""
        Marks the start of a workpiece with the given UID.
        """
        __match_args__ = ("uid", "_tag",)
        @property
        def uid(self) -> builtins.str: ...
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, uid: builtins.str, _tag: builtins.bool) -> Marker.WorkpieceStart: ...
    
    @typing.final
    class WorkpieceEnd(Marker):
        r"""
        Marks the end of a workpiece with the given UID.
        """
        __match_args__ = ("uid", "_tag",)
        @property
        def uid(self) -> builtins.str: ...
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, uid: builtins.str, _tag: builtins.bool) -> Marker.WorkpieceEnd: ...
    
    @typing.final
    class ProcessStart(Marker):
        r"""
        Marks the start of a process with versioned JSON parameters.
        """
        __match_args__ = ("uid", "params", "_tag",)
        @property
        def uid(self) -> builtins.str: ...
        @property
        def params(self) -> builtins.str: ...
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, uid: builtins.str, params: builtins.str, _tag: builtins.bool) -> Marker.ProcessStart: ...

    @typing.final
    class ProcessEnd(Marker):
        r"""
        Marks the end of a process with the given UID.
        """
        __match_args__ = ("uid", "_tag",)
        @property
        def uid(self) -> builtins.str: ...
        @property
        def _tag(self) -> builtins.bool: ...
        def __new__(cls, uid: builtins.str, _tag: builtins.bool) -> Marker.ProcessEnd: ...

    ...

@typing.final
class RotaryMappingSpec:
    r"""
    Per-layer rotary axis mapping configuration.
    """
    @property
    def layer_uid(self) -> builtins.str:
        r"""
        UID of the layer this rotary config applies to.
        """
    @property
    def diameter(self) -> builtins.float:
        r"""
        Rotary workpiece diameter (mm).
        """
    @property
    def gear_ratio(self) -> builtins.float:
        r"""
        Gear ratio.
        """
    @property
    def reverse(self) -> builtins.bool:
        r"""
        When true, negate computed degree values.
        """
    @property
    def axis_position_3d(self) -> builtins.list[builtins.float]:
        r"""
        Axis mount position (x, y, z).
        """
    @property
    def cylinder_dir(self) -> builtins.list[builtins.float]:
        r"""
        Cylinder direction vector (x, y, z).
        """
    @property
    def rotary_axis(self) -> builtins.str:
        r"""
        Rotary axis name (e.g. "A", "B", "C").
        """
    @property
    def replaced_axis(self) -> typing.Optional[builtins.str]:
        r"""
        Replaced world axis name or None for TRUE_4TH_AXIS.
        """
    @property
    def mm_per_rotation(self) -> builtins.float:
        r"""
        Millimetres per full rotation (0 = no conversion).
        """
    def __new__(cls, layer_uid: builtins.str, diameter: builtins.float, gear_ratio: builtins.float, reverse: builtins.bool, axis_position_3d: typing.Sequence[builtins.float], cylinder_dir: typing.Sequence[builtins.float], rotary_axis: builtins.str, replaced_axis: typing.Optional[builtins.str], mm_per_rotation: builtins.float) -> RotaryMappingSpec: ...

